name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.7.0
      with:
           node-version: 12.22.12
           
    - name : npm install 
      run:  npm install
          
    - name : npm build
      run: npm run build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zhonghaibin/mm_html:1.0
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
    - name: Push Docker images
      run: docker push  zhonghaibin/mm_html:1.0
          
    - name: SSH command
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{secrets.NAS_HOST}}
          username: ${{secrets.NAS_USERNAME}}
          port: ${{secrets.NAS_PORT}}
          password: ${{secrets.NAS_PASSWORD}}
          script: | # 重启更新镜像
             /usr/local/bin/docker pull zhonghaibin/mm_html:1.0
             /usr/local/bin/docker stop mm_html
             /usr/local/bin/docker rm mm_html
             /usr/local/bin/docker run --name=mm_html -d -p 8080:80  zhonghaibin/mm_html:1.0
       
          
