name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: SSH command runner
        uses: Evaneos/ssh-action@v0.1.0
        with:
            hosts: ${{secrets.NAS_HOST}}
            user: ${{secrets.NAS_USERNAME}}
            port: ${{secrets.NAS_PORT}}
            password: ${{secrets.NAS_PASSWORD}}
            commands: |
              sudo docker images
       
          
