name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: SSH command
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{secrets.NAS_HOST}}
            username: ${{secrets.NAS_USERNAME}}
            port: ${{secrets.NAS_PORT}}
            password: ${{secrets.NAS_PASSWORD}}
            script: |
                  echo ${{secrets.NAS_PASSWORD}} |sudo -S  git
           
       
          
